export const data = [
  {
    id: 1,
    name: "John Doe",
    age: "25",
    salary: "1000",
    job: "Developer",
    dateOfBirth: "1999-04-15",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: "30",
    salary: "1200",
    job: "Designer",
    dateOfBirth: "1994-08-22",
  },
  {
    id: 3,
    name: "Emily Johnson",
    age: "22",
    salary: "1100",
    job: "Project Manager",
    dateOfBirth: "2002-01-10",
  },
  {
    id: 4,
    name: "Michael Brown",
    age: "35",
    salary: "1500",
    job: "Engineer",
    dateOfBirth: "1989-11-05",
  },
  // {
  //   id: 5,
  //   name: "Chris Lee",
  //   age: "28",
  //   salary: "1300",
  //   job: "Data Analyst",
  //   dateOfBirth: "1996-03-18",
  // },
  // {
  //   id: 6,
  //   name: "Sarah Wilson",
  //   age: "32",
  //   salary: "1400",
  //   job: "Marketing Specialist",
  //   dateOfBirth: "1992-07-30",
  // },
  // {
  //   id: 7,
  //   name: "David Taylor",
  //   age: "29",
  //   salary: "1150",
  //   job: "Sales Representative",
  //   dateOfBirth: "1995-12-11",
  // },
  // {
  //   id: 8,
  //   name: "Jessica Clark",
  //   age: "26",
  //   salary: "1250",
  //   job: "Content Writer",
  //   dateOfBirth: "1998-09-25",
  // },
  // {
  //   id: 9,
  //   name: "Daniel Harris",
  //   age: "31",
  //   salary: "1350",
  //   job: "Consultant",
  //   dateOfBirth: "1993-06-07",
  // },
  // {
  //   id: 10,
  //   name: "Laura Martinez",
  //   age: "27",
  //   salary: "1050",
  //   job: "Administrative Assistant",
  //   dateOfBirth: "1997-02-20",
  // },
];
